name: main-group

on:
  merge_group:
    branches:
      - main

jobs:
  merge-to-main:
    runs-on: self-hosted
    steps:
      - name: test
        run: |
          echo "**************************************************"
          echo "                    MAIN GROUP                    "
          echo "**************************************************"
          