name: main-merge-group

on:
  merge_group:
    branches:
      - main

jobs:
  user_service:
    runs-on: self-hosted
    steps:
      - name: test
        run: |
          echo "**************************************************"
          echo "                   MERGE GROUP                    "
          echo "**************************************************"
          