name: main-merge-group

on:
  merge_group:
    branches:
      - feat-testing

jobs:
  merge-group:
    runs-on: self-hosted
    steps:
      - name: test
        run: |
          echo "**************************************************"
          echo "                 MAIN MERGE GROUP                 "
          echo "**************************************************"
          